# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: openjverein build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Set up JDK 11 for x64
      uses: actions/setup-java@main
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64

    - name: Check out jameica
      uses: actions/checkout@main
      with:
        repository: willuhn/jameica
        token: ${{ secrets.SERVICE_ACCOUNT_PAT }}
        path: jameica
        
    - name: Build jameica
      working-directory: ./
      run: ant -noinput -buildfile jameica/build/build.xml
    
    - name: Check out hibiscus
      uses: actions/checkout@main
      with:
        repository: willuhn/hibiscus
        token: ${{ secrets.SERVICE_ACCOUNT_PAT }}
        path: hibiscus
        
    - name: Build hibiscus plugin
      working-directory: ./
      run: ant -noinput -buildfile hibiscus/build/build.xml

    - name: Checkout openjverein
      uses: actions/checkout@main
      with:
        path: jverein
    
    - name: Show Working directory
      run: pwd && ls
        
    - name: Build openjverein plugin
      working-directory: ./
      run: ant -noinput -buildfile jverein/build/build.xml
