# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: openjverein nightly release

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ closed ]
    branches:
      [ master ]

jobs:
  build:
    name: Building nightly release and upload to branch

    runs-on: ubuntu-22.04

    steps:
    - name: Set up JDK 11 for x64
      uses: actions/setup-java@main
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64

    - name: Check out jameica
      uses: actions/checkout@main
      with:
        repository: willuhn/jameica
        token: ${{ secrets.SERVICE_ACCOUNT_PAT }}
        path: jameica
        
    - name: Build jameica nightly
      working-directory: ./
      run: ant -noinput -buildfile jameica/build/build.xml nightly
    
    - name: Check out hibiscus
      uses: actions/checkout@main
      with:
        repository: willuhn/hibiscus
        token: ${{ secrets.SERVICE_ACCOUNT_PAT }}
        path: hibiscus
        
    - name: Build hibiscus nightly
      working-directory: ./
      run: ant -noinput -buildfile hibiscus/build/build.xml nightly

    - name: Checkout openjverein
      uses: actions/checkout@main
      with:
        path: jverein
    
    - name: Build openjverein plugin
      id: openjverein
      working-directory: ./
      run: |
        ant_output=$(ant -e -q -noinput -buildfile jverein/build/build.xml nightly)
        echo "$(echo -n grep "^SELECTED_VERSION" $ant_output)" >> ${GITHUB_OUTPUT}
        echo "$(echo -n grep "^SELECTED_PATH" $ant_output)" >> ${GITHUB_OUTPUT}
        echo "$(echo -n grep "^SELECTED_FILENAME" $ant_output)" >> ${GITHUB_OUTPUT}

    - name: Create git release
      uses: actions/create-release@main
      env:
        GITHUB_TOKEN: ${{ secrets.SERVICE_ACCOUNT_PAT }}
      with:
        tag_name: v${{ steps.openjverein.outputs.SELECTED_VERSION }}
        release_name: v${{ steps.openjverein.outputs.SELECTED_VERSION }}
        draft: false
        prerelease: true

    - name: Upload binaries to git
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.SERVICE_ACCOUNT_PAT }}
        file: ./jverein/${{ steps.openjverein.outputs.SELECTED_PATH }}
        asset_name: ${{ steps.openjverein.outputs.SELECTED_FILENAME }}
        tag: v${{ steps.openjverein.outputs.SELECTED_VERSION }}
        overwrite: true
