# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: openjverein nightly release

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ closed ]
    branches:
      [ master ]

jobs:
  build:
    name: Building nightly release and upload to branch

    runs-on: ubuntu-22.04

    steps:
    - name: Set up JDK 11 for x64
      uses: actions/setup-java@main
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64

    - name: Check out jameica
      uses: actions/checkout@main
      with:
        repository: willuhn/jameica
        token: ${{ secrets.SERVICE_ACCOUNT_PAT }}
        path: jameica
        
    - name: Build jameica nightly
      working-directory: ./
      run: ant -noinput -buildfile jameica/build/build.xml nightly
    
    - name: Check out hibiscus
      uses: actions/checkout@main
      with:
        repository: willuhn/hibiscus
        token: ${{ secrets.SERVICE_ACCOUNT_PAT }}
        path: hibiscus
        
    - name: Build hibiscus nightly
      working-directory: ./
      run: ant -noinput -buildfile hibiscus/build/build.xml nightly

    - name: Checkout openjverein
      uses: actions/checkout@main
      with:
        path: jverein
    
    - name: Build openjverein plugin
      id: openjverein
      working-directory: ./
      run: |
        ant_output=$(ant -e -q -noinput -buildfile jverein/build/build.xml nightly)
        ssa="SELECTED_VERSION="
        ssb=".zip"
        text="${ant_output#*${ssa}}"
        text="${text%${ssb}*}.zip"
        tmp_version=$(echo $text | sed -rn 's/^([^[:blank:]]*).*$/\1/p')

        ssa="SELECTED_FILENAME="
        text="${ant_output#*${ssa}}"
        text="${text%${ssb}*}.zip"
        tmp_filename=$(echo $text | sed -rn 's/^([^[:blank:]]*).*$/\1/p')

        ssa="SELECTED_PATH="
        text="${ant_output#*${ssa}}"
        text="${text%${ssb}*}.zip"
        tmp_path=$(echo $text | sed -rn 's/^([^[:blank:]]*).*$/\1/p')

        echo "selected_version=$tmp_version" >> $GITHUB_OUTPUT
        echo "selected_filename=$tmp_filename" >> $GITHUB_OUTPUT
        echo "selected_path=$tmp_path" >> $GITHUB_OUTPUT

        echo "### version: $tmp_version | filename: $tmp_filename | path: $tmp_path" >> $GITHUB_STEP_SUMMARY

    - name: Create git release
      uses: actions/create-release@main
      env:
        GITHUB_TOKEN: ${{ secrets.SERVICE_ACCOUNT_PAT }}
      with:
        tag_name: v${{ steps.openjverein.outputs.selected_version }}
        release_name: Nightly release ${{ steps.openjverein.outputs.selected_version }}
        draft: false
        prerelease: true

    - name: Upload binaries to git
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.SERVICE_ACCOUNT_PAT }}
        tag: v${{ steps.openjverein.outputs.selected_version }}
        file: ./jverein/${{ steps.openjverein.outputs.selected_path }}
        asset_name: ${{ steps.openjverein.outputs.selected_filename }}
        overwrite: true
